/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CapacityMonitor_CONSTANTS_H
#define CapacityMonitor_CONSTANTS_H

#include "CapacityMonitor_types.h"

namespace com { namespace thriftcode {

class CapacityMonitorConstants {
 public:
  CapacityMonitorConstants();

};

extern const CapacityMonitorConstants g_CapacityMonitor_constants;

}} // namespace

#endif
