/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CapacityMonitor_constants.h"

namespace com { namespace thriftcode {

const CapacityMonitorConstants g_CapacityMonitor_constants;

CapacityMonitorConstants::CapacityMonitorConstants() {
}

}} // namespace

